Repository Me1tingPot/BE, pull requests merged in 2024-06, with the labels that each got.

#79 [Feature] 사용자 프로필 수정 구현
  src/main/java/meltingpot/server/auth/controller/AuthController.java
  src/main/java/meltingpot/server/domain/entity/Account.java
  src/main/java/meltingpot/server/user/controller/UserController.java
  src/main/java/meltingpot/server/user/controller/dto/UpdateBioRequestDto.java
  src/main/java/meltingpot/server/user/controller/dto/UpdateNameRequestDto.java
  src/main/java/meltingpot/server/user/controller/dto/UserResponseDto.java
  src/main/java/meltingpot/server/user/service/UserService.java
  src/main/java/meltingpot/server/user/service/dto/UpdateBioServiceDto.java
  src/main/java/meltingpot/server/user/service/dto/UpdateNameServiceDto.java
  src/main/java/meltingpot/server/util/ResponseCode.java
  src/main/java/meltingpot/server/util/VerificationUtil.java
Labels: ✨Feature, 💙 유정

#83 [Feature] 게시글 신고하기
  src/main/java/meltingpot/server/comment/service/CommentServiceImpl.java
  src/main/java/meltingpot/server/domain/repository/ReportRepository.java
  src/main/java/meltingpot/server/post/controller/PostController.java
  src/main/java/meltingpot/server/post/service/PostServiceImpl.java
  src/main/java/meltingpot/server/report/controller/ReportController.java
  src/main/java/meltingpot/server/report/converter/ReportConverter.java
  src/main/java/meltingpot/server/report/dto/ReportRequestDTO.java
  src/main/java/meltingpot/server/report/service/ReportService.java
  src/main/java/meltingpot/server/report/service/ReportServiceImpl.java
  src/main/java/meltingpot/server/util/ResponseCode.java
  src/main/resources/application.yml
Labels: ✨Feature, 💜 예윤

#87 [Feature] 사용자 프로필 이미지 조회 구현
  src/main/java/meltingpot/server/auth/controller/dto/ProfileImageSignupDto.java
  src/main/java/meltingpot/server/auth/controller/dto/SignupRequestDto.java
  src/main/java/meltingpot/server/auth/service/AuthService.java
  src/main/java/meltingpot/server/domain/entity/AccountProfileImage.java
  src/main/java/meltingpot/server/domain/entity/common/BaseEntity.java
  src/main/java/meltingpot/server/domain/repository/AccountProfileImageRepository.java
  src/main/java/meltingpot/server/domain/repository/AccountRepository.java
  src/main/java/meltingpot/server/user/controller/UserController.java
  src/main/java/meltingpot/server/user/controller/dto/UserResponseDto.java
  src/main/java/meltingpot/server/user/service/UserService.java
  src/main/java/meltingpot/server/user/service/dto/UserImagesResponseDto.java
Labels: ✨Feature, 💙 유정

#89 [Feat] AccessToken, RefreshToken 재발급 구현
  src/main/java/meltingpot/server/auth/controller/AuthController.java
  src/main/java/meltingpot/server/auth/controller/dto/ReissueTokenRequestDto.java
  src/main/java/meltingpot/server/auth/controller/dto/ReissueTokenResponseDto.java
  src/main/java/meltingpot/server/auth/service/AuthService.java
  src/main/java/meltingpot/server/config/TokenProvider.java
Labels: ✨Feature, 💙 유정

#92 [Chore] 지역 코드 최신화
  src/main/java/meltingpot/server/area/controller/AreaController.java
  src/main/java/meltingpot/server/area/dto/AreaResponse.java
  src/main/java/meltingpot/server/area/service/AreaService.java
  src/main/java/meltingpot/server/domain/entity/Area.java
  src/main/java/meltingpot/server/domain/repository/AreaRepository.java
  src/main/java/meltingpot/server/party/dto/PartyCreateRequest.java
  src/main/java/meltingpot/server/party/dto/PartyNearbySearchRequest.java
  src/main/java/meltingpot/server/party/dto/PartySearchRequest.java
  src/main/java/meltingpot/server/party/service/PartySearchService.java
Labels: 🧽 Chore, 🧡 민준

#93 [Refactor] 토큰 재발급 방식을 Body -> Header로 수정
  src/main/java/meltingpot/server/auth/controller/AuthController.java
  src/main/java/meltingpot/server/auth/service/AuthService.java
Labels: 🔨 Refactor, 💙 유정

#94 [Chore] 지역 좌표 변환을 코드 기반으로 동작하게 하라
  src/main/java/meltingpot/server/area/service/AreaService.java
Labels: 🧽 Chore, 🧡 민준

#95 feat : 마이페이지 사용자 이미지 추가 / 수정 / 삭제 구현
  src/main/java/meltingpot/server/auth/controller/AuthController.java
  src/main/java/meltingpot/server/auth/controller/dto/ProfileImageRequestDto.java
  src/main/java/meltingpot/server/auth/controller/dto/SignupRequestDto.java
  src/main/java/meltingpot/server/domain/entity/AccountProfileImage.java
  src/main/java/meltingpot/server/domain/repository/AccountProfileImageRepository.java
  src/main/java/meltingpot/server/user/controller/UserController.java
  src/main/java/meltingpot/server/user/controller/dto/NewProfileImageRequestDto.java
  src/main/java/meltingpot/server/user/service/UserService.java
  src/main/java/meltingpot/server/util/ResponseCode.java
Labels: ✨Feature, 💙 유정

#101 [Feat] 댓글 수정하기
  src/main/java/meltingpot/server/comment/controller/CommentController.java
  src/main/java/meltingpot/server/comment/service/CommentService.java
  src/main/java/meltingpot/server/comment/service/CommentServiceImpl.java
  src/main/java/meltingpot/server/domain/entity/comment/Comment.java
  src/main/java/meltingpot/server/util/ResponseCode.java
  src/main/resources/application.yml
Labels: ✨Feature, 💜 예윤

#103 feat : 채팅방 목록 조회 기획 변경 적용
  src/main/java/meltingpot/server/chat/dto/ChatRoomGetResponse.java
Labels: ✨Feature, 💛 예원

#105 feat : 채팅 메세지 조회 기획 변경 적용
  src/main/java/meltingpot/server/chat/controller/ChatRoomController.java
  src/main/java/meltingpot/server/chat/dto/ChatMessageGetResponse.java
  src/main/java/meltingpot/server/chat/dto/ChatMessagePageResponse.java
  src/main/java/meltingpot/server/chat/service/ChatRoomQueryService.java
  src/main/java/meltingpot/server/chat/service/WebSocketService.java
  src/main/java/meltingpot/server/domain/entity/Account.java
  src/main/java/meltingpot/server/domain/entity/chat/ChatMessage.java
Labels: ✨Feature, 💛 예원

#106 feat : 요청 url 변경
  src/main/java/meltingpot/server/chat/controller/ChatController.java
  src/main/java/meltingpot/server/chat/controller/ChatRoomController.java
  src/main/java/meltingpot/server/chat/dto/ChatRoomDetailGetResponse.java
  src/main/java/meltingpot/server/chat/dto/PageGetRequest.java
  src/main/java/meltingpot/server/chat/service/ChatRoomQueryService.java
Labels: ✨Feature, 💛 예원

#107 refactor : 요청 방식 변경
  src/main/java/meltingpot/server/chat/controller/ChatRoomController.java
  src/main/java/meltingpot/server/chat/dto/ChatRoomAlarmUpdateRequest.java
  src/main/java/meltingpot/server/chat/service/ChatRoomService.java
Labels: 🔨 Refactor, 💛 예원

#109 feat : 채팅방 나가기 기능 구현
  src/main/java/meltingpot/server/chat/controller/ChatRoomController.java
  src/main/java/meltingpot/server/chat/dto/ChatRoomsPageResponse.java
  src/main/java/meltingpot/server/chat/service/ChatRoomQueryService.java
  src/main/java/meltingpot/server/chat/service/ChatRoomService.java
  src/main/java/meltingpot/server/domain/repository/chat/ChatMessageRepository.java
  src/main/java/meltingpot/server/util/ResponseCode.java
Labels: ✨Feature, 💛 예원

#113 [Feat] 메인 화면 API 추가
  src/main/java/meltingpot/server/domain/entity/party/Party.java
  src/main/java/meltingpot/server/domain/specification/party/PartySpecification.java
  src/main/java/meltingpot/server/party/controller/PartySearchController.java
  src/main/java/meltingpot/server/party/dto/PartyCoordRequest.java
  src/main/java/meltingpot/server/party/dto/PartyCreateRequest.java
  src/main/java/meltingpot/server/party/dto/PartySearchRequest.java
  src/main/java/meltingpot/server/party/service/PartySearchService.java
  src/main/java/meltingpot/server/party/service/PartyService.java
Labels: ✨Feature, 🧡 민준

#115 refactor : 소켓 jwt 인증 로직
  src/main/java/meltingpot/server/config/JwtChannelInterceptor.java
  src/main/java/meltingpot/server/config/WebSocketConfig.java
  src/main/java/meltingpot/server/config/WebSocketSecurityConfig.java
Labels: 🔨 Refactor, 💛 예원

#116 [Feat] 푸시 알림 기능 추가
  build.gradle
  src/main/java/meltingpot/server/auth/controller/dto/SigninRequestDto.java
  src/main/java/meltingpot/server/auth/controller/dto/SignupRequestDto.java
  src/main/java/meltingpot/server/auth/service/AuthService.java
  src/main/java/meltingpot/server/auth/service/dto/SigninServiceDto.java
  src/main/java/meltingpot/server/domain/entity/AccountPushToken.java
  src/main/java/meltingpot/server/domain/repository/AccountPushTokenRepository.java
  src/main/java/meltingpot/server/util/push/PushConfig.java
  src/main/java/meltingpot/server/util/push/PushService.java
  src/main/resources/application.yml
Labels: ✨Feature, 🧡 민준

#118 Feature/#117
  src/main/java/meltingpot/server/auth/service/AuthService.java
  src/main/java/meltingpot/server/chat/controller/ChatController.java
  src/main/java/meltingpot/server/chat/controller/WebSocketController.java
  src/main/java/meltingpot/server/chat/service/ChatRoomQueryService.java
  src/main/java/meltingpot/server/chat/service/ChatService.java
  src/main/java/meltingpot/server/chat/service/WebSocketService.java
  src/main/java/meltingpot/server/config/ChatErrorHandler.java
  src/main/java/meltingpot/server/config/JwtChannelInterceptor.java
  src/main/java/meltingpot/server/config/JwtFilter.java
  src/main/java/meltingpot/server/config/TokenProvider.java
  src/main/java/meltingpot/server/config/WebSocketSecurityConfig.java
  src/main/java/meltingpot/server/domain/entity/chat/SocketSession.java
  src/main/java/meltingpot/server/util/push/PushConfig.java
  src/main/java/meltingpot/server/util/push/PushService.java
Labels: 🐛 Bug Fix, 💛 예원
