Repository Me1tingPot/BE, pull requests merged in 2024-05, with the labels that each got.

#2 [Chore] Swagger, SpringSecurity, ResponseTemplate 기본 세팅
  .gitignore
  .gradle/8.7/checksums/checksums.lock
  .gradle/8.7/executionHistory/executionHistory.lock
  .gradle/8.7/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .idea/gradle.xml
  .idea/misc.xml
  build.gradle
  src/main/java/meltingpot/server/config/SecurityConfig.java
  src/main/java/meltingpot/server/config/SwaggerConfig.java
  src/main/java/meltingpot/server/util/ResponseCode.java
  src/main/java/meltingpot/server/util/ResponseData.java
  src/main/resources/application.yml
Labels: 🧽 Chore

#3 [Chore] Swagger, SpringSecurity, ResponseTemplate 기본 세팅
  .gitignore
  .gradle/8.7/checksums/checksums.lock
  .gradle/8.7/executionHistory/executionHistory.lock
  .gradle/8.7/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .idea/gradle.xml
  .idea/misc.xml
  build.gradle
  src/main/java/meltingpot/server/config/SecurityConfig.java
  src/main/java/meltingpot/server/config/SwaggerConfig.java
  src/main/java/meltingpot/server/util/ResponseCode.java
  src/main/java/meltingpot/server/util/ResponseData.java
  src/main/resources/application.yml
Labels: 💙 유정, 🧽 Chore

#4 Revert "[Chore] Swagger, SpringSecurity, ResponseTemplate 기본 세팅"
  .gitignore
  .gradle/8.7/checksums/checksums.lock
  .gradle/8.7/executionHistory/executionHistory.lock
  .gradle/8.7/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .idea/gradle.xml
  .idea/misc.xml
  build.gradle
  src/main/java/meltingpot/server/config/SecurityConfig.java
  src/main/java/meltingpot/server/config/SwaggerConfig.java
  src/main/java/meltingpot/server/util/ResponseCode.java
  src/main/java/meltingpot/server/util/ResponseData.java
  src/main/resources/application.yml
Labels: 🔨 Refactor, 💙 유정

#7 [Feat] 유저 엔티티 생성
  src/main/java/meltingpot/server/domain/entity/User.java
  src/main/java/meltingpot/server/domain/entity/UserProfileImage.java
Labels: ✨Feature, 💙 유정

#8 [Chore] fixed untracked files
  .gradle/8.7/checksums/checksums.lock
  .gradle/8.7/dependencies-accessors/gc.properties
  .gradle/8.7/executionHistory/executionHistory.lock
  .gradle/8.7/fileChanges/last-build.bin
  .gradle/8.7/fileHashes/fileHashes.lock
  .gradle/8.7/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/vcs-1/gc.properties
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/vcs.xml
Labels: 💙 유정, 🧽 Chore

#10 [Feat] 채팅 엔티티 생성
  src/main/java/meltingpot/server/domain/entity/chat/Chat.java
  src/main/java/meltingpot/server/domain/entity/chat/ChatRoom.java
  src/main/java/meltingpot/server/domain/entity/chat/ChatUser.java
  src/main/java/meltingpot/server/domain/entity/chat/enums/Alarm.java
  src/main/java/meltingpot/server/domain/entity/common/BaseEntity.java
Labels: ✨Feature, 💛 예원

#25 Refactor : 회원 도메인명 변경
  src/main/java/meltingpot/server/domain/entity/Account.java
  src/main/java/meltingpot/server/domain/entity/AccountProfileImage.java
  src/main/java/meltingpot/server/domain/entity/Comment.java
  src/main/java/meltingpot/server/domain/entity/Image.java
  src/main/java/meltingpot/server/domain/entity/Post.java
  src/main/java/meltingpot/server/domain/entity/Report.java
  src/main/java/meltingpot/server/domain/entity/chat/Chat.java
  src/main/java/meltingpot/server/domain/entity/chat/ChatUser.java
  src/main/java/meltingpot/server/domain/entity/party/Party.java
  src/main/java/meltingpot/server/domain/entity/party/PartyImage.java
  src/main/java/meltingpot/server/domain/entity/party/PartyParticipant.java
  src/main/java/meltingpot/server/domain/entity/party/PartyWishlist.java
Labels: 🔨 Refactor, 💙 유정

#36 [Feat] 댓글 작성하기
  .idea/dataSources.local.xml
  src/main/java/meltingpot/server/comment/controller/CommentController.java
  src/main/java/meltingpot/server/comment/converter/CommentConverter.java
  src/main/java/meltingpot/server/comment/dto/CommentRequestDTO.java
  src/main/java/meltingpot/server/comment/dto/CommentResponseDTO.java
  src/main/java/meltingpot/server/comment/service/CommentService.java
  src/main/java/meltingpot/server/comment/service/CommentServiceImpl.java
  src/main/java/meltingpot/server/domain/entity/Account.java
  src/main/java/meltingpot/server/domain/entity/Comment.java
  src/main/java/meltingpot/server/domain/entity/common/BaseEntity.java
  src/main/java/meltingpot/server/domain/repository/CommentRepository.java
  src/main/java/meltingpot/server/post/controller/PostController.java
  src/main/java/meltingpot/server/post/converter/PostConverter.java
  src/main/java/meltingpot/server/post/dto/PostImageDTO.java
  src/main/java/meltingpot/server/post/dto/PostRequestDTO.java
  src/main/java/meltingpot/server/post/dto/PostResponseDTO.java
  src/main/java/meltingpot/server/post/service/PostService.java
  src/main/java/meltingpot/server/post/service/PostServiceImpl.java
  src/main/java/meltingpot/server/util/ResponseCode.java
Labels: ✨Feature, 💜 예윤

#51 [Fix] 403 에러 수정
  src/main/java/meltingpot/server/config/SecurityConfig.java
  src/main/java/meltingpot/server/config/TokenProvider.java
  src/main/java/meltingpot/server/post/service/PostServiceImpl.java
Labels: 🐛 Bug Fix, 🧡 민준

#52 [Feature] 파티 내용 조회 기능 구현
  src/main/java/meltingpot/server/domain/entity/party/PartyReport.java
  src/main/java/meltingpot/server/domain/repository/party/PartyReportRepository.java
  src/main/java/meltingpot/server/party/controller/PartyController.java
  src/main/java/meltingpot/server/party/dto/PartyReportRequest.java
  src/main/java/meltingpot/server/party/service/PartyService.java
  src/main/java/meltingpot/server/util/ResponseCode.java
Labels: ✨Feature, 🧡 민준

#58 [Chore] 배포 관련 설정
  .github/workflows/deploy.yml
  build.gradle
Labels: 🌏 Deploy, 🧡 민준

#61 [Chore] Github Actions를 Self-hosted runner에서 실행하라
  .github/workflows/deploy.yml
Labels: 🧽 Chore, 🧡 민준

#62 [Feature] 파티 검색 관련 기능 구현
  src/main/java/meltingpot/server/area/controller/AreaController.java
  src/main/java/meltingpot/server/area/dto/AreaResponse.java
  src/main/java/meltingpot/server/area/service/AreaService.java
  src/main/java/meltingpot/server/domain/entity/Area.java
  src/main/java/meltingpot/server/domain/entity/party/enums/PartyTemporalFilter.java
  src/main/java/meltingpot/server/domain/repository/AreaRepository.java
  src/main/java/meltingpot/server/domain/repository/party/PartyRepository.java
  src/main/java/meltingpot/server/domain/specification/party/PartySpecification.java
  src/main/java/meltingpot/server/party/controller/PartySearchController.java
  src/main/java/meltingpot/server/party/dto/PartySearchRequest.java
  src/main/java/meltingpot/server/party/service/PartySearchService.java
  src/main/java/meltingpot/server/util/ResponseCode.java
Labels: ✨Feature, 🧡 민준

#63 [Fix] 파티 검색시 지역이 정상적으로 검색되지 않는 문제를 수정하라
  src/main/java/meltingpot/server/domain/specification/party/PartySpecification.java
  src/main/java/meltingpot/server/party/service/PartySearchService.java
Labels: 🐛 Bug Fix, 🧡 민준

#64 [Feature] 내 주변 파티 조회 기능 구현
  src/main/java/meltingpot/server/party/controller/PartySearchController.java
  src/main/java/meltingpot/server/party/dto/PartyNearbySearchRequest.java
  src/main/java/meltingpot/server/party/service/PartySearchService.java
Labels: ✨Feature, 🧡 민준

#65 [Feature] 이미지 업로드 공통 컴포넌트 구현
  build.gradle
  src/main/java/meltingpot/server/util/r2/FileService.java
  src/main/java/meltingpot/server/util/r2/FileUploadResponse.java
  src/main/java/meltingpot/server/util/r2/R2Config.java
  src/main/resources/application.yml
Labels: ✨Feature, 🧡 민준

#66 [Fix] 배포 후 tomcat restart를 하도록 수정하라
  .github/workflows/deploy.yml
Labels: 🐛 Bug Fix, 🧡 민준

#67 [Feature] 파티 주최 관련 기능 구현
  src/main/java/meltingpot/server/domain/entity/party/Party.java
  src/main/java/meltingpot/server/domain/repository/party/PartyContentRepository.java
  src/main/java/meltingpot/server/domain/repository/party/PartyImageRepository.java
  src/main/java/meltingpot/server/domain/repository/party/PartyRepository.java
  src/main/java/meltingpot/server/party/controller/PartyController.java
  src/main/java/meltingpot/server/party/dto/PartyCreateRequest.java
  src/main/java/meltingpot/server/party/service/PartyService.java
  src/main/java/meltingpot/server/util/ResponseCode.java
Labels: ✨Feature, 🧡 민준

#69 [Feature] 파티 정보에 주최자 정보를 포함하도록 수정
  src/main/java/meltingpot/server/domain/entity/Account.java
  src/main/java/meltingpot/server/domain/repository/party/PartyParticipantRepository.java
  src/main/java/meltingpot/server/domain/repository/party/PartyRepository.java
  src/main/java/meltingpot/server/party/dto/PartyOwnerResponse.java
  src/main/java/meltingpot/server/party/dto/PartyResponse.java
Labels: ✨Feature, 🧡 민준

#71 [Feat] 커뮤니티 글 목록 조회
  src/main/java/meltingpot/server/config/SecurityConfig.java
  src/main/java/meltingpot/server/domain/repository/PostRepository.java
  src/main/java/meltingpot/server/post/controller/PostController.java
  src/main/java/meltingpot/server/post/converter/PostConverter.java
  src/main/java/meltingpot/server/post/dto/PostResponseDTO.java
  src/main/java/meltingpot/server/post/service/PostService.java
  src/main/java/meltingpot/server/post/service/PostServiceImpl.java
  src/main/java/meltingpot/server/util/ResponseCode.java
Labels: ✨Feature, 💜 예윤

#73 [FEAT] 사용자 마이페이지 프로필 조회 구현
  src/main/java/meltingpot/server/config/SecurityConfig.java
  src/main/java/meltingpot/server/config/SwaggerConfig.java
  src/main/java/meltingpot/server/domain/entity/AccountProfileImage.java
  src/main/java/meltingpot/server/domain/repository/AccountProfileImageRepository.java
  src/main/java/meltingpot/server/user/controller/UserController.java
  src/main/java/meltingpot/server/user/controller/dto/UserResponseDto.java
  src/main/java/meltingpot/server/user/service/UserService.java
  src/main/java/meltingpot/server/util/ResponseCode.java
Labels: 📑 Docs, ✨Feature, 💙 유정

#74 [Feature] 로그아웃 기능 구현
  src/main/java/meltingpot/server/auth/controller/AuthController.java
  src/main/java/meltingpot/server/auth/service/AuthService.java
  src/main/java/meltingpot/server/domain/entity/RefreshToken.java
  src/main/java/meltingpot/server/user/controller/UserController.java
Labels: ✨Feature, 💙 유정
