Repository Me1tingPot/BE, pull requests merged in 2024-07, with the labels that each got.

#120 feat : 유저 프로필 조회
  src/main/java/meltingpot/server/chat/controller/ChatRoomController.java
  src/main/java/meltingpot/server/chat/dto/ChatMessageGetResponse.java
  src/main/java/meltingpot/server/chat/dto/ChatMessagePageResponse.java
  src/main/java/meltingpot/server/chat/dto/ChatRoomGetResponse.java
  src/main/java/meltingpot/server/chat/dto/ChatRoomsPageResponse.java
  src/main/java/meltingpot/server/chat/service/ChatRoomQueryService.java
  src/main/java/meltingpot/server/chat/service/WebSocketService.java
Labels: ✨Feature, 💛 예원

#121 fix : 유저 프로필 기본 이미지 설정
  src/main/java/meltingpot/server/chat/service/ChatRoomQueryService.java
Labels: ✨Feature, 💛 예원

#125 Feature: 마이페이지 파티 참여 내역 조회 구현
  src/main/java/meltingpot/server/domain/repository/party/PartyRepository.java
  src/main/java/meltingpot/server/user/controller/UserController.java
  src/main/java/meltingpot/server/user/service/UserService.java
  src/main/java/meltingpot/server/util/Constants.java
Labels: ✨Feature, 💙 유정

#126 [Feature] 회원 탈퇴 마킹 처리 및 카카오 로그인 구현
  build.gradle
  src/main/java/meltingpot/server/auth/controller/AuthController.java
  src/main/java/meltingpot/server/auth/controller/dto/OAuthSignInRequestDto.java
  src/main/java/meltingpot/server/auth/controller/dto/OAuthSignupRequestDto.java
  src/main/java/meltingpot/server/auth/oauth/OAuthUserDetails.java
  src/main/java/meltingpot/server/auth/oauth/kakao/KaKaoTokenDto.java
  src/main/java/meltingpot/server/auth/oauth/kakao/KakaoDto.java
  src/main/java/meltingpot/server/auth/oauth/kakao/KakaoService.java
  src/main/java/meltingpot/server/auth/service/AuthService.java
  src/main/java/meltingpot/server/auth/service/OAuthService.java
  src/main/java/meltingpot/server/auth/service/dto/OAuthSignInResponseDto.java
  src/main/java/meltingpot/server/config/TokenProvider.java
  src/main/java/meltingpot/server/domain/entity/Account.java
  src/main/java/meltingpot/server/domain/entity/MsgEntity.java
  src/main/java/meltingpot/server/domain/entity/enums/OAuthType.java
  src/main/java/meltingpot/server/domain/repository/AccountRepository.java
  src/main/java/meltingpot/server/domain/repository/party/PartyParticipantRepository.java
  src/main/java/meltingpot/server/domain/repository/party/PartyRepository.java
  src/main/java/meltingpot/server/exception/ExceptionAdvice.java
  src/main/java/meltingpot/server/user/controller/UserController.java
  src/main/java/meltingpot/server/user/service/UserService.java
  src/main/java/meltingpot/server/util/ErrorCode.java
  src/main/java/meltingpot/server/util/ResponseCode.java
  src/main/java/meltingpot/server/util/SecurityUtil.java
  src/main/resources/application.yml
Labels: ✨Feature, 💙 유정

#131 🐛 [BUG] 댓글 목록 버그 수정
  src/main/java/meltingpot/server/comment/controller/CommentController.java
  src/main/java/meltingpot/server/comment/converter/CommentConverter.java
  src/main/java/meltingpot/server/comment/dto/CommentResponseDTO.java
  src/main/java/meltingpot/server/comment/service/CommentService.java
  src/main/java/meltingpot/server/comment/service/CommentServiceImpl.java
  src/main/java/meltingpot/server/domain/entity/comment/Comment.java
  src/main/java/meltingpot/server/domain/entity/comment/CommentImage.java
  src/main/java/meltingpot/server/domain/repository/CommentRepository.java
  src/main/java/meltingpot/server/post/controller/PostController.java
  src/main/java/meltingpot/server/post/converter/PostConverter.java
  src/main/java/meltingpot/server/post/dto/PostResponseDTO.java
  src/main/java/meltingpot/server/post/service/PostService.java
  src/main/java/meltingpot/server/post/service/PostServiceImpl.java
  src/main/java/meltingpot/server/util/ResponseCode.java
Labels: 🐛 Bug Fix, 💜 예윤

#134 [REFACTOR] 커뮤니티 코드 리팩터링
  src/main/java/meltingpot/server/comment/controller/CommentController.java
  src/main/java/meltingpot/server/comment/converter/CommentConverter.java
  src/main/java/meltingpot/server/comment/converter/CommentImageConverter.java
  src/main/java/meltingpot/server/comment/dto/CommentCreateRequest.java
  src/main/java/meltingpot/server/comment/dto/CommentRequestDTO.java
  src/main/java/meltingpot/server/comment/dto/CommentResponseDTO.java
  src/main/java/meltingpot/server/comment/dto/CommentsListResponse.java
  src/main/java/meltingpot/server/comment/service/CommentService.java
  src/main/java/meltingpot/server/comment/service/CommentServiceImpl.java
  src/main/java/meltingpot/server/domain/entity/comment/Comment.java
  src/main/java/meltingpot/server/domain/entity/comment/CommentImage.java
  src/main/java/meltingpot/server/domain/entity/post/PostImage.java
  src/main/java/meltingpot/server/domain/repository/CommentRepository.java
  src/main/java/meltingpot/server/domain/repository/PostRepository.java
  src/main/java/meltingpot/server/post/controller/PostController.java
  src/main/java/meltingpot/server/post/converter/PostConverter.java
  src/main/java/meltingpot/server/post/converter/PostImageConverter.java
  src/main/java/meltingpot/server/post/dto/PostCreateRequest.java
  src/main/java/meltingpot/server/post/dto/PostDetailResponse.java
  src/main/java/meltingpot/server/post/dto/PostImageDTO.java
  src/main/java/meltingpot/server/post/dto/PostRequestDTO.java
  src/main/java/meltingpot/server/post/dto/PostResponseDTO.java
  src/main/java/meltingpot/server/post/dto/PostsListResponse.java
  src/main/java/meltingpot/server/post/service/PostService.java
  src/main/java/meltingpot/server/post/service/PostServiceImpl.java
  src/main/java/meltingpot/server/util/ResponseCode.java
Labels: 🔨 Refactor, 💜 예윤

#135 [FEATURE] 게시글 수정하기
  src/main/java/meltingpot/server/comment/controller/CommentController.java
  src/main/java/meltingpot/server/post/controller/PostController.java
  src/main/java/meltingpot/server/post/dto/PostDetailResponse.java
  src/main/java/meltingpot/server/post/service/PostService.java
  src/main/java/meltingpot/server/util/ResponseCode.java
Labels: ✨Feature, 💜 예윤

#137 Feature/#132
  src/main/java/meltingpot/server/comment/controller/CommentController.java
  src/main/java/meltingpot/server/comment/dto/CommentsListResponse.java
  src/main/java/meltingpot/server/comment/service/CommentService.java
  src/main/java/meltingpot/server/domain/entity/comment/Comment.java
  src/main/java/meltingpot/server/post/controller/PostController.java
  src/main/java/meltingpot/server/post/service/PostService.java
  src/main/java/meltingpot/server/util/ResponseCode.java
Labels: ✨Feature, 💜 예윤

#138 [Feature] 게시글 임시저장 API #136
  src/main/java/meltingpot/server/comment/dto/CommentsListResponse.java
  src/main/java/meltingpot/server/comment/service/CommentService.java
  src/main/java/meltingpot/server/domain/entity/post/Post.java
  src/main/java/meltingpot/server/domain/repository/CommentImageRepository.java
  src/main/java/meltingpot/server/domain/repository/CommentRepository.java
  src/main/java/meltingpot/server/domain/repository/PostRepository.java
  src/main/java/meltingpot/server/post/controller/PostController.java
  src/main/java/meltingpot/server/post/dto/PostDetailResponse.java
  src/main/java/meltingpot/server/post/service/PostService.java
  src/main/java/meltingpot/server/util/ResponseCode.java
Labels: ✨Feature, 💜 예윤

#140 [Refactor] 카카오 로그인 SDK 방식으로 변경
  src/main/java/meltingpot/server/auth/controller/dto/OAuthSignInRequestDto.java
  src/main/java/meltingpot/server/auth/oauth/kakao/KakaoDto.java
  src/main/java/meltingpot/server/auth/oauth/kakao/KakaoService.java
  src/main/java/meltingpot/server/auth/service/OAuthService.java
Labels: 🔨 Refactor, 💙 유정
